name: Auto Commit README

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update README.md
      run: |
        echo "Last updated: $(date)" >> README.md

    - name: Commit changes
      run: |
        git config --global user.name "AbdulQadeer-55"
        git config --global user.email "qadeermemon100@gmail.com"
        git add README.md
        git commit -m "Update README: $(date +'%Y-%m-%d %H:%M:%S')"
    
    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
